src/flixter/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

src/flixter/app/models/course.rb
class Course < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :user
    has_many :sections
    has_many :enrollments
  
    validates :title, presence: true
    validates :description, presence: true
    validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
  end

src/flixter/app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :course
    belongs_to :user
end

src/flixter/app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :section
    mount_uploader :video, VideoUploader


    include RankedModel
    ranks :row_order, with_same: :section_id

    def next_lesson
        lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
        if lesson.blank? && section.next_section
            return section.next_section.lessons.rank(:row_order).first
        end
        return lesson
    end

end

src/flixter/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/flixter/app/models/section.rb
class Section < ApplicationRecord
    belongs_to :course
    has_many :lessons

    include RankedModel
    ranks :row_order, with_same: :course_id

    def next_section
        section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
        return section
    end

    validates :title, presence: true
    #validates :description, presence: true
    #validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
end

src/flixter/app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

src/flixter/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
end

src/flixter/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def index
      @courses = Course.all
    end

    def show
      @course = Course.find(params[:id])
    end
  end

src/flixter/app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :authenticate_user!

    def show
        
    end
end

src/flixter/app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
    before_action :authenticate_user!

    def create
        current_user.enrollments.create(course: current_course)
        redirect_to course_path(current_course)
    end

    private

    def current_course
        @current_course ||= Course.find(params[:course_id])
    end
end

src/flixter/app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  helper_method :current_user

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

src/flixter/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_enrollment_for_lesson

    def show
        
    end

    private

    def require_enrollment_for_lesson
        if current_user && current_user.enrolled_in?(current_lesson.section.course) == false
          flash[:notice] = "You must be enrolled to view this lesson."
          redirect_to course_path(current_lesson.section.course)
    
        end
      end

    helper_method :current_lesson
    def current_lesson
       @current_lesson ||= Lesson.find(params[:id]) 
    end
end

src/flixter/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index

    end

    def privacy
        
    end

end

src/flixter/app/helpers/charges_helper.rb
module ChargesHelper
end

src/flixter/app/helpers/courses_helper.rb
module CoursesHelper
end

src/flixter/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

src/flixter/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

src/flixter/app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

src/flixter/app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

src/flixter/app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

src/flixter/app/helpers/lessons_helper.rb
module LessonsHelper
end

src/flixter/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

src/flixter/app/views/dashboards/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>What I'm Learning</h1>
  <% current_user.enrolled_courses.each do |course| %>
    <h3 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h3>
    <br />
    <%= image_tag course.image.to_s, class: 'img-fluid' %>
    <br />
    <div class="row">
        <div class="col-12 col-sm-8">
            <%= course.description %>
        </div>
        <div class="col-12 col-sm-4 text-center">
            <%= link_to "More Info...", course_path(course), class: 'btn btn-lg btn-primary' %>
        </div>
    </div>
    <hr class="col-8 offset-2">
    <br class="clr" />
  <% end %>

  <h1>What I'm Teaching</h1>
  <% current_user.courses.each do |course| %>
    <h3 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h3>
    <br />
    <%= image_tag course.image.to_s, class: 'img-fluid' %>
    <br />
    <div class="row">
        <div class="col-12 col-sm-8">
            <%= course.description %>
        </div>

        <div class="col-12 col-sm-4 text-center">
            <%= link_to "More Info...", course_path(course), class: 'btn btn-lg btn-primary' %>
        </div>
    </div>
    <hr class="col-8 offset-2">
    <br class="clr" />
  <% end %>
</div>

src/flixter/app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Learn Magic from the Pros</h1>
    <br />
    <h2>I'm an illusionist, Michael.</h2>
    <br />
    <%= link_to 'Learn More', courses_path, class: 'btn btn-success' %>
    <br /><br />
  </div>
</div>

<br />
<div class="row feature text-center">
  <div class="booyah-box">
    <div class="col-12 col-sm">
      <h3>Amazing Courses</h3>
      <br />
      <p>Choose from any number of courses to study with amazing teachers.</p>
    </div>
  </div>

  <div class="col-12 col-sm">
    <div class="booyah-box">
      <h3>Learn At Your Own Pace</h3>
      <br />
      <p>Enroll and access a course archive of lessons.</p>
    </div>
  </div>

  <div class="col-12 col-sm">
    <div class="booyah-box">
      <h3>Join our Community</h3>
      <br />
      <p>Learn with a community of like-minded individuals.</p>
    </div>
  </div>
</div>

src/flixter/app/views/static_pages/privacy.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>Privacy Policy</h1>

  <p>
    We don't believe in Privacy Policies because YOLO.
  </p>
</div>